version: '3.8'

networks:
  laravel_network:

volumes:
  db_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    command: sh -c "chown -R www-data:www-data /var/www/html /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html /var/www/html/storage /var/www/html/bootstrap/cache && apache2-foreground"
    ports:
      - "8090:80"  # Access Laravel on http://localhost:8090
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: paintingdb
      MYSQL_PASSWORD: 159357
      MYSQL_ROOT_PASSWORD: 159357
    volumes:
      - db_data:/var/lib/mysql
      - ./paintingdb.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"  # Access phpMyAdmin on http://localhost:8080
    depends_on:
      - db

